# Generated by Django 5.1.1 on 2024-10-28 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content_type', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], max_length=10)),
                ('release_year', models.PositiveIntegerField()),
                ('maturity_rating', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('writers', models.CharField(max_length=255)),
                ('stars', models.CharField(max_length=255)),
                ('genres', models.ManyToManyField(related_name='content', to='notes.genre')),
                ('languages', models.ManyToManyField(related_name='content', to='notes.language')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='notes.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
